import Kambing from "./assets/dummy.jpg"
import Susu from "./assets/Milk.png"

// Goat.js
export const Goat = [
    {
      id: 1,
      food_name: "Kambing Guling",
      food_category: "goat_main",
      food_quantity: 1,
      food_img: Kambing,
      price: 150000,
    },
    {
      id: 2,
      food_name: "Sate Kambing",
      food_category: "goat_main",
      food_quantity: 1,
      food_img: Kambing,
      price: 40000,
    },
    {
      id: 3,
      food_name: "Gulai Kambing",
      food_category: "goat_main",
      food_quantity: 1,
      food_img: Kambing,
      price: 35000,
    },
    {
      id: 4,
      food_name: "Kambing Tongseng",
      food_category: "goat_main",
      food_quantity: 1,
      food_img: Kambing,
      price: 35000,
    },
    {
      id: 5,
      food_name: "Kambing Kecil",
      food_category: "goat_main",
      food_quantity: 1,
      food_img: Kambing,
      price: 150000,
    },
    {
      id: 6,
      food_name: "Kambing",
      food_category: "goat_main",
      food_quantity: 1,
      food_img: Kambing,
      price: 40000,
    },
    {
      id: 7,
      food_name: "Kambing Soto",
      food_category: "goat_main",
      food_quantity: 1,
      food_img: Kambing,
      price: 35000,
    },
    {
      id: 8,
      food_name: "Kambing Kari",
      food_category: "goat_main",
      food_quantity: 1,
      food_img: Kambing,
      price: 35000,
    },
    {
      id: 9,
      food_name: "Kambing Potong",
      food_category: "goat_main",
      food_quantity: 1,
      food_img: Kambing,
      price: 35000,
    },
    {
      id: 10,
      food_name: "Kambing Hidup",
      food_category: "goat_main",
      food_quantity: 1,
      food_img: Kambing,
      price: 35000,
    },
  ];
  
  // Milk.js
export const Milk = [
    {
      id: 1,
      food_name: "Susu Murni Segar",
      food_category: "fresh_milk",
      food_quantity: 1,
      food_img: Susu,
      price: 15000,
    },
    {
      id: 6,
      food_name: "Yogurt Plain",
      food_category: "milk_processed",
      food_quantity: 1,
      food_img: Susu,
      price: 20000,
    },
    {
      id: 7,
      food_name: "susu dingin",
      food_category: "milk_processed",
      food_quantity: 1,
      food_img: Susu,
      price: 25000,
    },
    {
      id: 8,
      food_name: "Susu Bubuk",
      food_category: "milk_powder",
      food_quantity: 1,
      food_img: Susu,
      price: 30000,
    },
    {
      id: 5,
      food_name: "Susu Beku",
      food_category: "fresh_milk",
      food_quantity: 1,
      food_img: Susu,
      price: 15000,
    },
    {
      id: 2,
      food_name: "Yogurt Plain",
      food_category: "milk_processed",
      food_quantity: 1,
      food_img: Susu,
      price: 20000,
    },
    {
      id: 3,
      food_name: "susu dingin",
      food_category: "milk_processed",
      food_quantity: 1,
      food_img: Susu,
      price: 25000,
    },
    {
      id: 4,
      food_name: "Susu Bubuk",
      food_category: "milk_powder",
      food_quantity: 1,
      food_img: Susu,
      price: 30000,
    },
    {
      id: 3,
      food_name: "susu dingin",
      food_category: "milk_processed",
      food_quantity: 1,
      food_img: Susu,
      price: 25000,
    },
    {
      id: 4,
      food_name: "Susu Bubuk",
      food_category: "milk_powder",
      food_quantity: 1,
      food_img: Susu,
      price: 30000,
    },
  ];
  